# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x07\n\x05\x45mpty\"-\n\x08PeerInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\")\n\x08PeerList\x12\x1d\n\x05peers\x18\x01 \x03(\x0b\x32\x0e.chat.PeerInfo\"7\n\x0b\x43hatMessage\x12\x17\n\x0f\x61uthor_username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\x87\x01\n\x04\x43hat\x12\'\n\x08Register\x12\x0e.chat.PeerInfo\x1a\x0b.chat.Empty\x12\'\n\x08GetPeers\x12\x0b.chat.Empty\x1a\x0e.chat.PeerList\x12-\n\x0bSendMessage\x12\x11.chat.ChatMessage\x1a\x0b.chat.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_PEERINFO']._serialized_start=29
  _globals['_PEERINFO']._serialized_end=74
  _globals['_PEERLIST']._serialized_start=76
  _globals['_PEERLIST']._serialized_end=117
  _globals['_CHATMESSAGE']._serialized_start=119
  _globals['_CHATMESSAGE']._serialized_end=174
  _globals['_CHAT']._serialized_start=177
  _globals['_CHAT']._serialized_end=312
# @@protoc_insertion_point(module_scope)
